# Set env vars for AWS_* when launching - this config will refer to them.
# To specify prod flavor, set the environment variable SETTINGS_FLAVOR=prod

# example launching with this config, in a docker image:
# docker run -p 5000:5000 \
#     -e SETTINGS_FLAVOR=prod \
#     -e AWS_KEY=X \
#     -e AWS_SECRET=Y \
#     -e WORKER_SECRET_KEY=Z \
#     -e AWS_BUCKET=images \
#      blalor/s3-registry

prod:
    storage: s3
    storage_path: /images
    s3_encrypt: false
    s3_secure: true

    secret_key: _env:WORKER_SECRET_KEY

    s3_access_key: _env:AWS_KEY
    s3_secret_key: _env:AWS_SECRET

    boto_bucket: _env:AWS_BUCKET
    s3_bucket: _env:AWS_BUCKET

